language: php

php:
  - 7.0
  - 7.1


before_script:
  - composer self-update
  - composer install --dev --prefer-source --no-interaction
  - cp .env.travis .env
  - php artisan key:generate

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=PSR2